### ISSUE TITLE
Loading issues for projects with thousands of issues takes too long

### ISSUE THREAD

**Issue by mxcl** [Me1000/issues#147]
I wanted to use BugHub for mxcl/Homebrew and this is fine provided the app hasn't been unloaded by iOS, but otherwise it takes way too long (15 minutes, no joke) for it to be usable as a quick issue tool.

**Comment by Me1000** [comment]
This issue is fixed in the 1.5 update I submitted today. \n\nUnfortunately when I try to load the closed issues for homebrew it beings the app to a near halt. I have some ideas how To fix this too... But it won't make it into 1.5. \n\nThat said, this latest update should make the app usable for you.
